# Page settings
baseurl = "MadTalksSite.netlify.com"
title = "MADTalks"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = "skyzoom25@gmail.com"
  # Navigation
  [params.navigation]
    brand = "MADTalks"
    home = "Home"
    services = "Upcoming"
    work = "Discover"
    contact = "Previous"
    about = "About"
    
    

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "MADTalks"
    subtitle = 'sparking exploration <a  target="_blank"></a>'


# Microshort section
  [params.microshort]
    enable = true
    title = "THE STATE AND FUTURE OF CLOUD COMPUTING: November 15, 2017"
    description = "THE STATE AND FUTURE OF CLOUD COMPUTING: November 15, 2017"
    button = "sign up"


    [[params.microshort.item]]
      title = "About The Talk"
      description = "Jessica Tavasti Davis has seen the rapid growth and change of cloud computing within the government in the last decade. In spite of projections that the cloud market will top $400 billion by 2020, Davis argues that there still remains a key challenge: how people perceive the cloud. She makes the case that misconceptions about privacy and security are the main blocker for organizations to transition entirely to the cloud."
      icon = "icon-anchor"


   






# Microsoft section
  [params.microsoft]
    enable = true
    title = "Previous Talks"
    description = "THE STATE AND FUTURE OF CLOUD COMPUTING: November 15, 2017"
    button = "      "


    [[params.microsoft.item]]
      title = "About The Talk"
      description = "Jessica Tavasti Davis has seen the rapid growth and change of cloud computing within the government in the last decade. In spite of projections that the cloud market will top $400 billion by 2020, Davis argues that there still remains a key challenge: how people perceive the cloud. She makes the case that misconceptions about privacy and security are the main blocker for organizations to transition entirely to the cloud."
      icon = "icon-anchor"


    [[params.microsoft.item]]
      title = "Jessica Davis"
      img = "jessica.jpg"
      description = "Jessica Tavasti Davis has worked at Microsoft for over nine years, and she brings extensive expertise from a variety of roles and projects in the cloud field. She is currently Director of Business Applications for the US Public Sector, where she works with federal, state, and local governments to develop and implement Microsoft’s cloud solutions that enhance productivity, increase return on investment, and reduce costs."
      icon = "icon-layers2"

      
    [[params.microsoft.item]]
      title = ""
      img = "JESSTALK.JPG"
      description = ""
      icon = "icon-layers2"

      [[params.microsoft.item]]
      title = ""
      img = "JESSTALK2.JPG"
      description = ""
      icon = "icon-layers2"


    

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Mission"
    description = "MADTalks was created to spark exploration. In our talks, we hope to bring together the diverse perspectives of leaders in a wide range of fields to encourage debate in these areas, which we strongly believe can spur the development of new ideas and change ways of thinking. "
    url = "https://docs.google.com/forms/d/1gYSoFVC2_SNMKPUZ71t0RuvGt1peQY05U9gQjiHnwCc/edit"
    button = "Sign Up"
    icon = "icon-rocket"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "What is MADTalks?"
    description = "MADTalks is an independently organized speaker series at James Madison High School in northern Virginia. A platform for conversation and analysis, MADTalks fosters discussion about trends in diverse fields—from neuroscience to capital markets to cloud computing—through live 30-minute interview-style talks. MADTalks also gives high school students the unique opportunity to meet leaders in these fields and learn from their expertise."
    url = "https://docs.google.com/forms/d/1-gmkiy57PCVSBA8q1b6FRRg7DAz4e-7jO9dyAhpUuA4/edit"
    button = "Sign Up"
    icon = "icon-bulb"
    img = "img_8.jpg"

  

 # [params.intro.video]
 #   enable = true
  #  title = "Watch the video"
 #   icon = "icon-play2"
 #   url = "https://vimeo.com/234611234"


  



  # Services section
  [params.services]
    enable = true
    title = "Our Next Talk"
    description = ""
    url = "https://docs.google.com/forms/d/1gYSoFVC2_SNMKPUZ71t0RuvGt1peQY05U9gQjiHnwCc/edit"
    button = "sign up"

    [[params.services.item]]
      title = "Solve a Rubik’s Cube and Become a Millionaire"
      description = "Sze Wong | February 23, 2018"
      icon = "icon-cube"
      url = "https://docs.google.com/forms/d/1N_x9-G4gh1wfsmisldqZo3tUFq8fkKxqj3VaPmTWFcM/edit"
    button = "Sign Up"
      
      

      [params.services1]
    enable = true
    title = "Future Talks"
    description = ""

    
     # Services section
  [params.uber]
    enable = true
    title = "Services"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.uber.item]]
      title = "Brand &amp; Strategy"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-anchor"

    [[params.uber.item]]
      title = "Web &amp; Interface"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.uber.item]]
      title = "Photo &amp; Video"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-video2"

      [[params.uber.item]]
      title = "CMS &amp; eCommerce"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-monitor"



    
      

    

    [[params.services1.item]]
      title = "The Power of Social Media in 2018 American Politics"
      description = "Jeb Ory | March 7, 2018"
      icon = "icon-twitter"

      [[params.services1.item]]
      title = "Money and Millenials "
      description = "March 22, 2018 | Lynne Celia"
      icon = "icon-money"
    



  # About section
  [params.about]
    enable = true
    title = "Meet The Team"
    description = ""


[[params.about.item]]
      name = "Sky Zoom"
      position = "Founder and Executive Director"
      description = "Head of Content"
      img = "SKYZOOMPIC.JPG"
      alt = "Person2"
      social = [
        
        ["icon-linkedin", "https://www.linkedin.com/in/skyzoom/"]
      ]

      [[params.about.item]]
      name = "Luke Dobrovic"
      position = "Executive Director"
      description = "Head of Operations   "
      img = "LUKEPIC.JPG"
      alt = "Person3"
      social = [
        
        ["icon-linkedin", "https://www.linkedin.com/in/luke-dobrovic-8797a1154/"]
      ]
      
    
    

    [[params.about.item]]
      name = "Khuslen Jargalan"
      position = "Head of Outreach"
      description = "       "
      img = "khuska.JPG"
      alt = "Person3"
   


[[params.about.item]]
      name = "Amartya Banerjee"
      position = "Head of IT and Software"
      description = "Web Developer"
      img = "amartya1.JPG"
      alt = "Person1"
      social = [
        
        
        ["icon-linkedin", "www.linkedin.com/in/amartyambanerjee"],
        ["icon-github", "https://github.com/Amartyabb"],
      ]

# Learn section
  [params.Learn]
    enable = true
    title = "Meet The Team"
    description = "The founders of MadTalks"


[[params.Learn.item]]
      name = "Sky Zoom"
      position = "CEO"
      description = "Cool Kid"
      img = "skyzoom.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "https://www.facebook.com/abhxi"],
        ["icon-github", "#"]
      ]

    
    

    [[params.Learn.item]]
      name = "Khuslen Jargalan"
      position = "CEO"
      description = ""
      img = "khuska.jpg"
      alt = "Person3"
      social = [
        
      ]      

      [[params.Learn.item]]
      name = "Luke Dobrevich"
      position = "CEO"
      description = ""
      img = "luke.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]   

[[params.Learn.item]]
      name = "Amartya Banerjee"
      position = "Web Developer"
      description = "Cool Kid"
      img = "amartya1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "https://www.facebook.com/profile.php?id=100011150208688"],
        ["icon-linkedin", "#"]
      ]



  # Counters section
  #[params.counters]
  #  enable = true
 #   title = "Stats"
 #   background = "full_image_1.jpg"

 #   [[params.counters.item]]
 #     description = "GB of space"
 #     icon = "icon-floppy-o"
 #     from = 0
 #     to = 289
 #     interval = 50
 #     speed = 5000

 #   [[params.counters.item]]
 #     description = "Lines of code"
 #     icon = "icon-code"
 #     from = 0
 #     to = 2343409
 #     interval = 50
 #     speed = 5000

 #   [[params.counters.item]]
  #    description = "Cups of coffee"
 #     icon = "icon-cup"
 #     from = 0
 #     to = 1302
 #     interval = 50
 #     speed = 5000

 #   [[params.counters.item]]
 #     description = "Employees"
 #     icon = "icon-people"
  #    from = 0
 #     to = 4
 #     interval = 50
 #     speed = 1000



   #   [[params.introbutton.item]]
    
   # url = "https://docs.google.com/forms/d/1gYSoFVC2_SNMKPUZ71t0RuvGt1peQY05U9gQjiHnwCc/edit"
  #  button = "Sign Up"
    



  # Contact section
  [params.contact]

    enable = true
    map = true
    title = "Get in touch"
    description = "Need something to get done? Have questions? Write us an email and we will get back to you super fast."
    
    # Available icons: http://simplelineicons.com/
    details = [
        
        ["icon-phone", ""],
        ["icon-envelope", "skyzoom25@gmail.com"],
        ["icon-facebook-square", '<a href="" target="_blank"></a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"


# Chipotle section
  [params.chipotle]
    enable = true
    title = "        "
    description = "Marketing the Burrito Bowl: September 27, 2017"

    [[params.chipotle.item]]
      title = "About The Talk"
      description = "Every day, about one million people eat Chipotle. Jake Park takes us inside the fast-casual restaurant’s unconventional philosophy of reaching and retaining customers and its “advertising as education” approach to marketing. He also discusses the defined meaning of Chipotle’s brand promise after several catastrophic food safety crises. "
      icon = "icon-anchor"


    [[params.chipotle.item]]
      title = "Jake Park"
      img = "jake.jpg"
      description = "Jake Park helps design the framework necessary for Chipotle to reach its customers and expand its market both locally and nationally. Previously, he was Senior Brand Associate for Capital One, working specializing in small businesses."
      icon = "icon-layers2"

      [[params.chipotle.item]]
      title = ""
      img = "chipotle2.jpg"
      description = ""
      icon = "icon-layers2"
    
# Work section
  [params.work]
    enable = true
    title = "Our Talks"
    description = "  "
    footertext = ''

    [[params.work.row]]
      img = "chipotle6.jpg"
      alt = "Image2"
      title = "Marketing the Burrito Bowl"
      subtitle = "Jake Park: September 27, 2017"
      
    url = "second.html"
    button = "Learn More"

    [[params.work.row]]
      img = "JESSTALK2.JPG"
      alt = "Image2"
      title = "THE STATE AND FUTURE OF CLOUD COMPUTING"
      subtitle = "Jessica Davis: November 15, 2017"

      url = "#"
    button = "Learn More"
    
  
  # Chipotle section
  [params.chipotleprev]
    enable = true
    title = "           "
    description = "Marketing the Burrito Bowl: September 27, 2017"

    [[params.chipotleprev.item]]
      title = "About The Talk"
      description = "Every day, about one million people eat Chipotle. Jake Park takes us inside the fast-casual restaurant’s unconventional philosophy of reaching and retaining customers and its “advertising as education” approach to marketing. He also discusses the defined meaning of Chipotle’s brand promise after several catastrophic food safety crises. "
      icon = "icon-anchor"


    [[params.chipotleprev.item]]
      title = "Jake Park"
      img = "jake.jpg"
      description = "Jake Park helps design the framework necessary for Chipotle to reach its customers and expand its market both locally and nationally. Previously, he was Senior Brand Associate for Capital One, working specializing in small businesses."
      icon = "icon-layers2"

      [[params.chipotleprev.item]]
      title = ""
      img = "chipotle2.jpg"
      description = ""
      icon = "icon-layers2"
    