# Page settings
baseurl = "MadTalksSite.netlify.com"
title = "MADTalks"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = "skyzoom25@gmail.com"
  # Navigation
  [params.navigation]
    brand = "MADTalks"
    home = "Home"
    work = "Discover"
   
    services = "Services"
    about = "About"
    contact = "Upcoming"
    testimonials = "Previous"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "MADTalks"
    subtitle = 'sparking exploration <a  target="_blank"></a>'


# Microshort section
  [params.microshort]
    enable = true
    title = "THE STATE AND FUTURE OF CLOUD COMPUTING: November 15, 2017"
    description = "THE STATE AND FUTURE OF CLOUD COMPUTING: November 15, 2017"
    button = "sign up"


    [[params.microshort.item]]
      title = "About The Talk"
      description = "Since its introduction in 2006, cloud computing is changing the way we watch TV, do our homework, listen to music, and just about every other aspect of our life, whether we realize it or not. Cloud computing is also changing the way businesses and the governments across the world operate. In this MADTalk, Jessica Tavasti Davis, Director of Business Applications for the US Public Sector at Microsoft, shares insights from working with cloud for nine years. With a track record of empowering digital transformation with Microsoft cloud across the public sector, Jessica discusses Microsoft’s niche in the cloud industry, the relationship between her company and competitors like Amazon Web Services and Google Cloud Platform, and the biggest potentials for growth and challenge of cloud computing in the coming years, among other topics."
      icon = "icon-anchor"


   

    






# Microsoft section
  [params.microsoft]
    enable = true
    title = "Previous Talk"
    description = "THE STATE AND FUTURE OF CLOUD COMPUTING: November 15, 2017"
    button = "      "


    [[params.microsoft.item]]
      title = "About The Talk"
      description = "Since its introduction in 2006, cloud computing is changing the way we watch TV, do our homework, listen to music, and just about every other aspect of our life, whether we realize it or not. Cloud computing is also changing the way businesses and the governments across the world operate. In this MADTalk, Jessica Tavasti Davis, Director of Business Applications for the US Public Sector at Microsoft, shares insights from working with cloud for nine years. With a track record of empowering digital transformation with Microsoft cloud across the public sector, Jessica discusses Microsoft’s niche in the cloud industry, the relationship between her company and competitors like Amazon Web Services and Google Cloud Platform, and the biggest potentials for growth and challenge of cloud computing in the coming years, among other topics."
      icon = "icon-anchor"


    [[params.microsoft.item]]
      title = "Jessica Davis"
      img = "jessica.jpg"
      description = "Jessica Tavasti Davis has worked at Microsoft for over nine years, and she brings extensive expertise from a variety of roles and projects in the cloud field. She is currently Director of Business Applications for the US Public Sector, where she works with federal, state, and local governments to develop and implement Microsoft’s cloud solutions that enhance productivity, increase return on investment, and reduce costs."
      icon = "icon-layers2"

      
    [[params.microsoft.item]]
      title = ""
      img = "JESSTALK.JPG"
      description = ""
      icon = "icon-layers2"

      [[params.microsoft.item]]
      title = ""
      img = "JESSTALK2.JPG"
      description = ""
      icon = "icon-layers2"


    

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Mission"
    description = "As more and more high schoolers go into college with an interest in business, MADTalks strives to connect high school students with industry leaders in the Washington, DC metro area. This speaker series hosts talks with those at the forefront of today’s innovative and corporate world, with the goal of sharing valuable insights and promoting dialogue among students and businessmen and businesswomen. "
    url = "https://docs.google.com/forms/d/1-gmkiy57PCVSBA8q1b6FRRg7DAz4e-7jO9dyAhpUuA4/edit"
    button = "Sign Up"
    icon = "icon-rocket"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "What is MADTalks?"
    description = "MADTalks is a speaker series based at James Madison High School in Vienna, Virginia. Its management team — Sky Zoom, Luke Dobrovic, Khuslen Jargalan, and Amartya Banerjee — created the organization to expose high school students interested in business to industry leaders, with the goal of sparking the students’ further exploration and interest. MADTalks seeks to bring to these students the diverse perspectives and experiences from leaders in the worlds of finance, technology, and media. "
    url = "https://docs.google.com/forms/d/1-gmkiy57PCVSBA8q1b6FRRg7DAz4e-7jO9dyAhpUuA4/edit"
    button = "Sign Up"
    icon = "icon-bulb"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Logistics"
    description = "talks are held in Warhawk Hall during the Warhawk Time block, which runs from approximately 9:50am to 10:25am. Talks will be held approximately once every 3-4 weeks. Venue preparation is done by the management team the day prior, and clean-up is done by the management team immediately following each talk. "
    url = "https://docs.google.com/forms/d/1-gmkiy57PCVSBA8q1b6FRRg7DAz4e-7jO9dyAhpUuA4/edit"
    button = "Sign Up"
    icon = "icon-wrench"
    img = "img_10.jpg"

 # [params.intro.video]
 #   enable = true
  #  title = "Watch the video"
 #   icon = "icon-play2"
 #   url = "https://vimeo.com/234611234"


  



  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "What we can do for you"

    [[params.services.item]]
      title = "Purpose"
      description = "MADTalks has the ability to connect students with insights from luminaires that they would not otherwise have the opportunity to be exposed to. It is a non-disruptive in-school supplement to core classroom education."
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Content"
      description = "The three main industries MADTalks seeks to bring leaders from are technology, finance, and media. Talks with leaders focus on the strategic management and direction of the corporations they work for, the latest developments in their fields, and their personal experiences leading to their success."
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Significance"
      description = "Such insights provide students with a potentially eye-opening introduction to fields that may spark interest for future exploration, as well as open doors for new networks of connection to the professional world."
      icon = "icon-video2"

      [[params.services.item]]
      title = "Benefits"
      description = "Corporations whose leaders speak at MADTalks events also benefit by developing closer community relations and demonstrating greater corporate social responsibility, two issues that have gained increasing attention in the private sector. They may also be able to develop early relationships with possible future college interns and employees."      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "Meet The Team"
    description = ""


[[params.about.item]]
      name = "Sky Zoom"
      position = "Executive Director"
      description = "Director of Content"
      img = "SKYZOOMPIC.JPG"
      alt = "Person2"
      social = [
        
        ["icon-linkedin", "https://www.linkedin.com/in/skyzoom/"]
      ]

      [[params.about.item]]
      name = "Luke Dobrovic"
      position = "Executive Director"
      description = "Director of Operations   "
      img = "LUKEPIC.JPG"
      alt = "Person3"
      
    
    

    [[params.about.item]]
      name = "Khuslen Jargalan"
      position = "Director of Outreach"
      description = "       "
      img = "khuska.JPG"
      alt = "Person3"
   


[[params.about.item]]
      name = "Amartya Banerjee"
      position = "Director of IT and Software"
      description = "Web Developer"
      img = "amartya1.JPG"
      alt = "Person1"
      social = [
        
        
        ["icon-linkedin", "#"],
        ["icon-github", "github.io/amartyabb"],
      ]

# Learn section
  [params.Learn]
    enable = true
    title = "Meet The Team"
    description = "The founders of MadTalks"


[[params.Learn.item]]
      name = "Sky Zoom"
      position = "CEO"
      description = "Cool Kid"
      img = "skyzoom.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "https://www.facebook.com/abhxi"],
        ["icon-github", "#"]
      ]

    
    

    [[params.Learn.item]]
      name = "Khuslen Jargalan"
      position = "CEO"
      description = ""
      img = "khuska.jpg"
      alt = "Person3"
      social = [
        
      ]      

      [[params.Learn.item]]
      name = "Luke Dobrevich"
      position = "CEO"
      description = ""
      img = "luke.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]   

[[params.Learn.item]]
      name = "Amartya Banerjee"
      position = "Web Developer"
      description = "Cool Kid"
      img = "amartya1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "https://www.facebook.com/profile.php?id=100011150208688"],
        ["icon-linkedin", "#"]
      ]



  # Counters section
  #[params.counters]
  #  enable = true
 #   title = "Stats"
 #   background = "full_image_1.jpg"

 #   [[params.counters.item]]
 #     description = "GB of space"
 #     icon = "icon-floppy-o"
 #     from = 0
 #     to = 289
 #     interval = 50
 #     speed = 5000

 #   [[params.counters.item]]
 #     description = "Lines of code"
 #     icon = "icon-code"
 #     from = 0
 #     to = 2343409
 #     interval = 50
 #     speed = 5000

 #   [[params.counters.item]]
  #    description = "Cups of coffee"
 #     icon = "icon-cup"
 #     from = 0
 #     to = 1302
 #     interval = 50
 #     speed = 5000

 #   [[params.counters.item]]
 #     description = "Employees"
 #     icon = "icon-people"
  #    from = 0
 #     to = 4
 #     interval = 50
 #     speed = 1000



   #   [[params.introbutton.item]]
    
   # url = "https://docs.google.com/forms/d/1-gmkiy57PCVSBA8q1b6FRRg7DAz4e-#7jO9dyAhpUuA4/edit"
  #  button = "Sign Up"
    



  # Contact section
  [params.contact]

    enable = true
    map = true
    title = "Get in touch"
    description = "Need something to get done? Have questions? Write us an email and we will get back to you super fast."
    
    # Available icons: http://simplelineicons.com/
    details = [
        
        ["icon-phone", ""],
        ["icon-envelope", "skyzoom25@gmail.com"],
        ["icon-facebook-square", '<a href="" target="_blank"></a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"


# Chipotle section
  [params.chipotle]
    enable = true
    title = "        "
    description = "Marketing the Burrito Bowl: September 27, 2017"

    [[params.chipotle.item]]
      title = "About The Talk"
      description = "Today, about 1 million people will eat at Chipotle. The fast-casual food chain has pioneered and innovated in the restaurant industry, and in the last 10 years, its sales have increased by 400 percent. But this skyrocketing popularity of burritos and burrito bowls is different from just about every other restaurant in its market. Notably, it has a one-of-a-kind marketing strategy that steers away from conventional media to promote its products (ever seen a Chipotle TV commercial? Yeah, didn’t think so). In this talk, Chipotle Marketing Strategist Jake Park shared his valuable insights into the company’s unique method of reaching and attracting customers in the increasingly competitive fast-casual restaurant industry. "
      icon = "icon-anchor"


    [[params.chipotle.item]]
      title = "Jake Park"
      img = "jake.jpg"
      description = "Jake Park helps design the framework necessary for Chipotle to reach its customers and expand its market both locally and nationally. Previously, he was Senior Brand Associate for Capital One, working specializing in small businesses."
      icon = "icon-layers2"

      [[params.chipotle.item]]
      title = ""
      img = "chipotle2.jpg"
      description = ""
      icon = "icon-layers2"
    
# Work Section
     [params.work]
    enable = true
    title = "Gallery"
    description = "Here are some pictures from our last few talks"
    footertext = ''

    [[params.work.row]]
      img = "groupchipotle.jpg"
      alt = "Image2"
      

    [[params.work.row]]
      img = "chipotle4.jpg"
      alt = "Image2"
      

    [[params.work.row]]
      img = "JESSTALK3.JPG"
      alt = "Image3"
      

    [[params.work.row]]
      img = "JESSTALK6.JPG"
      alt = "Image4"
      

    [[params.work.row]]
      img = "JESSTALK4.JPG"
      alt = "Image5"
      

    [[params.work.row]]
      img = "JESSTALK5.JPG"
      alt = "Image6"
      

      [[params.work.row]]
      img = "chipotle6.jpg"
      alt = "Image6"
      

      [[params.work.row]]
      img = "chipotle7.jpg"
      alt = "Image6"

      [[params.work.row]]
      img = "chipotle8.jpg"
      alt = "Image6"
      
  
  # Chipotle section
  [params.chipotleprev]
    enable = true
    title = "           "
    description = "Marketing the Burrito Bowl: September 27, 2017"

    [[params.chipotleprev.item]]
      title = "About The Talk"
      description = "Today, about 1 million people will eat at Chipotle. The fast-casual food chain has pioneered and innovated in the restaurant industry, and in the last 10 years, its sales have increased by 400 percent. But this skyrocketing popularity of burritos and burrito bowls is different from just about every other restaurant in its market. Notably, it has a one-of-a-kind marketing strategy that steers away from conventional media to promote its products (ever seen a Chipotle TV commercial? Yeah, didn’t think so). In this talk, Chipotle Marketing Strategist Jake Park shared his valuable insights into the company’s unique method of reaching and attracting customers in the increasingly competitive fast-casual restaurant industry. "
      icon = "icon-anchor"


    [[params.chipotleprev.item]]
      title = "Jake Park"
      img = "jake.jpg"
      description = "Jake Park helps design the framework necessary for Chipotle to reach its customers and expand its market both locally and nationally. Previously, he was Senior Brand Associate for Capital One, working specializing in small businesses."
      icon = "icon-layers2"

      [[params.chipotleprev.item]]
      title = ""
      img = "chipotle2.jpg"
      description = ""
      icon = "icon-layers2"
    